// =========================================================
// REPORTS MODULE — Excel, PDF, CSV export
// =========================================================
import { getState, getFilteredPRCs } from './state.js';
import { fmtDate, toCSV, downloadText, downloadBlob, toast } from './utils.js';
import { calculateStatus, getPRCAge, calcAgeDays } from './status-engine.js';

const REPORT_COLUMNS = {
  prc: [
    { key: 'prNumber',        label: 'PR Number' },
    { key: 'status',          label: 'Status' },
    { key: 'department',      label: 'Department' },
    { key: 'job',             label: 'Job' },
    { key: 'priority',        label: 'Priority' },
    { key: 'engineer',        label: 'Engineer' },
    { key: 'allocationNumber',label: 'Allocation No.' },
    { key: 'allocationDate',  label: 'Allocation Date', accessor: r => fmtDate(r.allocationDate) },
    { key: 'rfqNumber',       label: 'RFQ No.' },
    { key: 'rfqDate',         label: 'RFQ Date',        accessor: r => fmtDate(r.rfqDate) },
    { key: 'tcdNumber',       label: 'TCD No.' },
    { key: 'tcdDate',         label: 'TCD Date',        accessor: r => fmtDate(r.tcdDate) },
    { key: 'poNumber',        label: 'PO No.' },
    { key: 'poDate',          label: 'PO Date',         accessor: r => fmtDate(r.poDate) },
    { key: 'vendorName',      label: 'Vendor' },
    { key: 'createdAt',       label: 'Created',         accessor: r => fmtDate(r.createdAt) },
    { key: 'remarks',         label: 'Remarks' }
  ]
};

/** Export to CSV */
export function exportCSV(reportType = 'prc') {
  const prcs = getFilteredPRCs();
  const cols = REPORT_COLUMNS[reportType] || REPORT_COLUMNS.prc;
  const csv  = toCSV(prcs, cols);
  const filename = `PRC_Report_${new Date().toISOString().split('T')[0]}.csv`;
  downloadText(csv, filename, 'text/csv');
  toast(`CSV exported — ${prcs.length} records`, 'success');
}

/** Export to Excel via SheetJS */
export function exportExcel(reportType = 'prc', title = 'PRC Procurement Report') {
  if (!window.XLSX) { toast('SheetJS not loaded', 'error'); return; }

  const prcs  = getFilteredPRCs();
  const cols  = REPORT_COLUMNS[reportType] || REPORT_COLUMNS.prc;
  const state = getState();

  // Cover sheet data
  const coverData = [
    ['ProcureTrack — Procurement Report'],
    ['Generated:', new Date().toLocaleString()],
    ['Generated By:', state.currentUser?.name || 'System'],
    ['Total Records:', prcs.length],
    ['Report Type:', title],
    []
  ];

  // Main data
  const headers = cols.map(c => c.label);
  const rows    = prcs.map(p =>
    cols.map(c => c.accessor ? c.accessor(p) : (p[c.key] ?? ''))
  );

  const wb = XLSX.utils.book_new();

  // Cover sheet
  const coverWS = XLSX.utils.aoa_to_sheet(coverData);
  XLSX.utils.book_append_sheet(wb, coverWS, 'Summary');

  // Data sheet
  const dataWS = XLSX.utils.aoa_to_sheet([headers, ...rows]);

  // Column widths
  dataWS['!cols'] = cols.map(c => ({ wch: Math.max(c.label.length, 15) }));

  XLSX.utils.book_append_sheet(wb, dataWS, 'PRC Data');

  // Material sheet
  const allMats = [];
  prcs.forEach(prc => {
    (prc.materials || []).forEach(m => {
      allMats.push([
        prc.prNumber, m.matCode, m.description, m.unit, m.quantity,
        m.processedQty || 0, m.pendingQty || 0, m.closedQty || 0,
        m.warehouse, m.poNumber, fmtDate(m.poDate), m.vendorName || m.vendor,
        fmtDate(m.deliveryDate), m.status
      ]);
    });
  });
  if (allMats.length) {
    const matWS = XLSX.utils.aoa_to_sheet([
      ['PR Number','Material Code','Description','Unit','Req Qty','Processed Qty','Pending Qty','Closed Qty','Warehouse','PO Number','PO Date','Vendor','Delivery Date','Status'],
      ...allMats
    ]);
    XLSX.utils.book_append_sheet(wb, matWS, 'Materials');
  }

  const filename = `PRC_Export_${new Date().toISOString().split('T')[0]}.xlsx`;
  XLSX.writeFile(wb, filename);
  toast(`Excel exported — ${prcs.length} records`, 'success');
}

/** Export to PDF via jsPDF */
export async function exportPDF(title = 'PRC Procurement Report') {
  if (!window.jspdf) { toast('jsPDF not loaded', 'error'); return; }

  const { jsPDF } = window.jspdf;
  const prcs      = getFilteredPRCs();
  const state     = getState();
  const doc       = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

  const primary   = [37, 99, 235];
  const pageW     = doc.internal.pageSize.getWidth();
  const pageH     = doc.internal.pageSize.getHeight();

  // Header
  doc.setFillColor(...primary);
  doc.rect(0, 0, pageW, 22, 'F');
  doc.setTextColor(255,255,255);
  doc.setFontSize(14);
  doc.setFont('helvetica','bold');
  doc.text('ProcureTrack — ' + title, 10, 14);
  doc.setFontSize(9);
  doc.setFont('helvetica','normal');
  doc.text(`Generated: ${new Date().toLocaleString()} | By: ${state.currentUser?.name}`, pageW - 10, 14, { align: 'right' });

  // Summary row
  const sum = state.statusSummary || {};
  doc.setTextColor(40,40,40);
  doc.setFontSize(9);
  doc.setFillColor(240, 244, 248);
  doc.rect(0, 22, pageW, 12, 'F');
  const sumItems = [
    `Total: ${prcs.length}`,
    `Completed: ${sum['Process Completed']||0}`,
    `Pending: ${sum['Pending']||0}`,
    `Partly: ${sum['Partly Completed']||0}`,
    `Awaiting: ${sum['Awaiting Offer']||0}`,
    `Inputs: ${sum['Inputs Required']||0}`
  ];
  sumItems.forEach((s, i) => {
    doc.text(s, 10 + i * 47, 30);
  });

  // Table using autoTable if available
  const cols = [
    'PR Number','Status','Department','Allocation No.','RFQ No.','TCD No.','PO No.','Vendor','Created'
  ];
  const rows = prcs.slice(0, 500).map(p => [
    p.prNumber, p.status, p.department,
    p.allocationNumber||'—', p.rfqNumber||'—', p.tcdNumber||'—',
    p.poNumber||'—', p.vendorName||'—', fmtDate(p.createdAt)
  ]);

  if (doc.autoTable) {
    doc.autoTable({
      head: [cols],
      body: rows,
      startY: 36,
      theme: 'striped',
      headStyles: { fillColor: primary, textColor: 255, fontSize: 8, fontStyle: 'bold' },
      bodyStyles: { fontSize: 7.5, cellPadding: 1.5 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      margin: { left: 5, right: 5 }
    });
  } else {
    // Basic fallback table
    let y = 40;
    doc.setFontSize(8);
    rows.forEach(r => {
      if (y > pageH - 15) { doc.addPage(); y = 20; }
      doc.text(r.join(' | '), 5, y);
      y += 6;
    });
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7.5);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount}`, pageW - 10, pageH - 5, { align: 'right' });
    doc.text('ProcureTrack — Confidential', 10, pageH - 5);
  }

  doc.save(`PRC_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  toast('PDF exported!', 'success');
}

/** Generate ageing report data calculated up to Process Completed / Partly Completed dates */
export function getAgeingReport() {
  const prcs = getFilteredPRCs().filter(p => !['Short Closed','Wrong PRC','PR Not Approved'].includes(p.status));
  return prcs.map(p => {
    const ageDays = getPRCAge(p);
    return { ...p, ageDays };
  }).sort((a,b) => (b.ageDays||0)-(a.ageDays||0));
}

